### PR TITLE
Implementation of from_vec initializer for FaceEncoding.

### PR DESCRIPTION
**Pull request by JSanchesDovichi**
Quick implementation to use a Vec<f64> to initialize a FaceEncoding struct.

### CODE REVIEW

**Comment by sunnyregion** [comment]
How to build the project. And How to create a demo ?

**Comment by JSanchesDovichi** [comment]
> How to build the project. And How to create a demo ?

To build: cargo build --features embed-all
To run tests: cargo test --test benchmarks --features embed-all
To run example: cargo run --example draw --features embed-all assets/obama_1.jpg outputs/obama_1.jpg

**Comment by sunnyregion** [comment]
> > How to build the project. And How to create a demo ?
> 
> To build: cargo build --features embed-all To run tests: cargo test --test benchmarks --features embed-all To run example: cargo run --example draw --features embed-all assets/obama_1.jpg outputs/obama_1.jpg

Thanks a lot .

BTW  I used Ubuntu

I do that "cargo build --features embed-all"  is right.

But I did that "cargo run --example draw --features embed-all assets/obama_1.jpg outputs/obama_1.jpg"

error[E0615]: attempted to take value of method `x` on type `&dlib_face_recognition::Point`
  --> examples/draw.rs:18:27
   |
18 |     image.put_pixel(point.x as u32, point.y as u32, colour);
   |                           ^ method, not a field
   |
help: use parentheses to call the method
   |
18 |     image.put_pixel(point.x() as u32, point.y as u32, colour);
   |                            ^^

error[E0615]: attempted to take value of method `y` on type `&dlib_face_recognition::Point`
  --> examples/draw.rs:18:43
   |
18 |     image.put_pixel(point.x as u32, point.y as u32, colour);
   |                                           ^ method, not a field
   |
help: use parentheses to call the method
   |
18 |     image.put_pixel(point.x as u32, point.y() as u32, colour);
   |                                            ^^

error[E0615]: attempted to take value of method `x` on type `&dlib_face_recognition::Point`
  --> examples/draw.rs:19:27
   |
19 |     image.put_pixel(point.x as u32 + 1, point.y as u32, colour);
   |                           ^ method, not a field
   |
help: use parentheses to call the method
   |
19 |     image.put_pixel(point.x() as u32 + 1, point.y as u32, colour);
   |                            ^^

error[E0615]: attempted to take value of method `y` on type `&dlib_face_recognition::Point`
  --> examples/draw.rs:19:47
   |
19 |     image.put_pixel(point.x as u32 + 1, point.y as u32, colour);
   |                                               ^ method, not a field
   |
help: use parentheses to call the method
   |
19 |     image.put_pixel(point.x as u32 + 1, point.y() as u32, colour);
   |                                                ^^

error[E0615]: attempted to take value of method `x` on type `&dlib_face_recognition::Point`
  --> examples/draw.rs:20:27
   |
20 |     image.put_pixel(point.x as u32 + 1, point.y as u32 + 1, colour);
   |                           ^ method, not a field
   |
help: use parentheses to call the method
   |
20 |     image.put_pixel(point.x() as u32 + 1, point.y as u32 + 1, colour);
   |                            ^^

error[E0615]: attempted to take value of method `y` on type `&dlib_face_recognition::Point`
  --> examples/draw.rs:20:47
   |
20 |     image.put_pixel(point.x as u32 + 1, point.y as u32 + 1, colour);
   |                                               ^ method, not a field
   |
help: use parentheses to call the method
   |
20 |     image.put_pixel(point.x as u32 + 1, point.y() as u32 + 1, colour);
   |                                                ^^

error[E0615]: attempted to take value of method `x` on type `&dlib_face_recognition::Point`
  --> examples/draw.rs:21:27
   |
21 |     image.put_pixel(point.x as u32, point.y as u32 + 1, colour);
   |                           ^ method, not a field
   |
help: use parentheses to call the method
   |
21 |     image.put_pixel(point.x() as u32, point.y as u32 + 1, colour);
   |                            ^^

error[E0615]: attempted to take value of method `y` on type `&dlib_face_recognition::Point`
  --> examples/draw.rs:21:43
   |
21 |     image.put_pixel(point.x as u32, point.y as u32 + 1, colour);
   |                                           ^ method, not a field
   |
help: use parentheses to call the method
   |
21 |     image.put_pixel(point.x as u32, point.y() as u32 + 1, colour);
   |                                            ^^

warning: use of deprecated associated function `image::DynamicImage::to_rgb`: replaced by `to_rgb8`
  --> examples/draw.rs:37:49
   |
37 |     let mut image = image::open(input).unwrap().to_rgb();
   |                                                 ^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

For more information about this error, try `rustc --explain E0615`.
warning: `dlib-face-recognition` (example "draw") generated 1 warning
error: could not compile `dlib-face-recognition` due to 8 previous errors; 1 warning emitted

**Comment by JSanchesDovichi** [comment]
> > > How to build the project. And How to create a demo ?
> > 
> > 
> > To build: cargo build --features embed-all To run tests: cargo test --test benchmarks --features embed-all To run example: cargo run --example draw --features embed-all assets/obama_1.jpg outputs/obama_1.jpg
> 
> Thanks a lot .
> 
> BTW I used Ubuntu
> 
> I do that "cargo build --features embed-all" is right.
> 
> But I did that "cargo run --example draw --features embed-all assets/obama_1.jpg outputs/obama_1.jpg"
> 
> error[E0615]: attempted to take value of method `x` on type `&dlib_face_recognition::Point` --> examples/draw.rs:18:27 | 18 | image.put_pixel(point.x as u32, point.y as u32, colour); | ^ method, not a field | help: use parentheses to call the method | 18 | image.put_pixel(point.x() as u32, point.y as u32, colour); | ^^
> 
> error[E0615]: attempted to take value of method `y` on type `&dlib_face_recognition::Point` --> examples/draw.rs:18:43 | 18 | image.put_pixel(point.x as u32, point.y as u32, colour); | ^ method, not a field | help: use parentheses to call the method | 18 | image.put_pixel(point.x as u32, point.y() as u32, colour); | ^^
> 
> error[E0615]: attempted to take value of method `x` on type `&dlib_face_recognition::Point` --> examples/draw.rs:19:27 | 19 | image.put_pixel(point.x as u32 + 1, point.y as u32, colour); | ^ method, not a field | help: use parentheses to call the method | 19 | image.put_pixel(point.x() as u32 + 1, point.y as u32, colour); | ^^
> 
> error[E0615]: attempted to take value of method `y` on type `&dlib_face_recognition::Point` --> examples/draw.rs:19:47 | 19 | image.put_pixel(point.x as u32 + 1, point.y as u32, colour); | ^ method, not a field | help: use parentheses to call the method | 19 | image.put_pixel(point.x as u32 + 1, point.y() as u32, colour); | ^^
> 
> error[E0615]: attempted to take value of method `x` on type `&dlib_face_recognition::Point` --> examples/draw.rs:20:27 | 20 | image.put_pixel(point.x as u32 + 1, point.y as u32 + 1, colour); | ^ method, not a field | help: use parentheses to call the method | 20 | image.put_pixel(point.x() as u32 + 1, point.y as u32 + 1, colour); | ^^
> 
> error[E0615]: attempted to take value of method `y` on type `&dlib_face_recognition::Point` --> examples/draw.rs:20:47 | 20 | image.put_pixel(point.x as u32 + 1, point.y as u32 + 1, colour); | ^ method, not a field | help: use parentheses to call the method | 20 | image.put_pixel(point.x as u32 + 1, point.y() as u32 + 1, colour); | ^^
> 
> error[E0615]: attempted to take value of method `x` on type `&dlib_face_recognition::Point` --> examples/draw.rs:21:27 | 21 | image.put_pixel(point.x as u32, point.y as u32 + 1, colour); | ^ method, not a field | help: use parentheses to call the method | 21 | image.put_pixel(point.x() as u32, point.y as u32 + 1, colour); | ^^
> 
> error[E0615]: attempted to take value of method `y` on type `&dlib_face_recognition::Point` --> examples/draw.rs:21:43 | 21 | image.put_pixel(point.x as u32, point.y as u32 + 1, colour); | ^ method, not a field | help: use parentheses to call the method | 21 | image.put_pixel(point.x as u32, point.y() as u32 + 1, colour); | ^^
> 
> warning: use of deprecated associated function `image::DynamicImage::to_rgb`: replaced by `to_rgb8` --> examples/draw.rs:37:49 | 37 | let mut image = image::open(input).unwrap().to_rgb(); | ^^^^^^ | = note: `#[warn(deprecated)]` on by default
> 
> For more information about this error, try `rustc --explain E0615`. warning: `dlib-face-recognition` (example "draw") generated 1 warning error: could not compile `dlib-face-recognition` due to 8 previous errors; 1 warning emitted

Hello!
These are some old problems regarding old syntax errors. They only occur when building the project directly nowadays. (Otherwise, using it in another project will work).

Both these are fixed in my latest commit, but i'll go through each one (there's just 2 in reality).

E0615: It simply means that the syntax for method calling is wrong. On these, instead of using point.x, you should use point.x(). -> These are already implemented in my latest commit.

And the last one the deprecation of DynamicImage::to_rgb method. It was replaced by to_rgb8() method, and the new syntax is already also available in my latest commit.

**Comment by HoKim98** [comment]
Hello, I'm the maintainer of this `dlib-face-recognition` library.

I updated this unmanaged library to make sure that all of major platforms support it.
In addition, various modifications, including suggested features such as #1 `Implementation of from_vec initializer for FaceEncoding`, will be incorporated into this latest source code.

However, some refactorings proposed will be rejected for now.
If you don't mind, could you open a separate PR for the refactoring?

Thank you.

**Pull request closed without merging**
