### PR TITLE
[Linux] cblas link fix

### PR DESCRIPTION
**Pull request by JSanchesDovichi**
Possible fix for #5

### CODE REVIEW

**Comment by HoKim98** [comment]
This commit may not be suitable for some platforms.
* [Ubuntu 21.10](https://github.com/snhdk/dlib-face-recognition/commit/c6dfd9a3fe5d10e418c39faaaa98828eec12d188)
* [Debian-like](https://github.com/FauxFaux/dlib-face-recognition/commit/4955ce44c7ebd861f64b61da861c7e99daad75c5)

**Comment by JSanchesDovichi** [comment]
That's what i thought would be a problem. I'm not sure if Rust supports distro-differentiation. Any ideias? I'm actually puzzled by why dlib on my platform does not work while linking against normal blas.

**Comment by HoKim98** [comment]
Sorry for the necrobumping, but I patched it by using `blas` only on Debian-like OS!

**Comment by JSanchesDovichi** [comment]
> Sorry for the necrobumping, but I patched it by using `blas` only on Debian-like OS!

Thanks! That helps a lot. I have no ideia why Arch doesn't want to link to blas directly. 
I was able to use openblas blas linking with a symlink, and also directly linking to openblas.
Maybe it's a interesting ideia to have a feature to link to openblas?

**Pull request closed without merging**
