### PR TITLE
Implement support feature for openblas linking

### PR DESCRIPTION
**Pull request by JSanchesDovichi**
Hello! Was busy before, but just did this little PR.

Just a new feature that enables linking to openblas + some code cleanup in build file.

Not sure how much it will affect everyone, but i got a noticeable performance jump in the CNN face detector using openblas (+ openmp):

cblas/debug:
hog: 5724ms
cnn: 11761ms
lp: 13ms

cblas/release:
hog: 107ms
cnn: 11796ms
lp: 2ms

openblas/debug:
hog: 5724ms
cnn: 1949ms
lp: 13ms

openblas/release:
hog: 105ms
cnn: 1895ms
lp: 3ms

### CODE REVIEW

**Comment by JSanchesDovichi** [comment]
@kerryeon  following up the discussion from #7

**Comment by HoKim98** [comment]
Thanks!! The benchmark result is quite interesting!

**Comment by JSanchesDovichi** [comment]
@kerryeon Hello! Any news on this?

**Comment by HoKim98** [comment]
@JSanchesDovichi Hello :) Thank you for calling my attention. Would you have some time checking the review?

**Review by JSanchesDovichi — COMMENTED** [review]
@kerryeon Done! I hope that´s good enough :D, do tell me if i forgot something.

**Comment by JSanchesDovichi** [comment]
@kerryeon Hello! Any news on this?

**Comment by HoKim98** [comment]
Merged with some patches!

**Pull request merged**
